# PASSWD: zhangguanzhang
ansible_ssh_port: 22
ansible_ssh_pass: zhangguanzhang

docker_version: '18.06'
ntp_domain1: 'cn.pool.ntp.org'
ntp_domain2: 's1b.time.edu.cn'
TimeZone: 'Asia/Shanghai'
kernel: true

VIP: '172.16.1.240'
VIP_NETMASK: 24
INTERFACE_NAME: eth0
# 下面前三个要改就一起改
SvcCIDR: 10.96.0.0/12
KubernetesClusterSVCIP: 10.96.0.1 # 默认占据SVC段的第一个ip,用于证书里SAN值
ClusterDns: 10.96.0.10  #修改SvcCIDR的画确保它的ip在CIDR内
PodCIDR: 10.244.0.0/16
ServiceNodePortRange: 30000-32767
ClusterDomain: cluster.local

#terminatedPodGcThreshold: 12500 #退出pod多少秒删除,默认12500

# kubelet更新自身状态频率 https://github.com/kubernetes-sigs/kubespray/blob/master/docs/kubernetes-reliability.md
# set one of the Fast | Medium | Low | default
nodeStatusUpdate: Medium
#nodeStatusUpdateFrequency: 10s
#nodeMonitorPeriod: 5s     # 如果改它确保它小于下面的值
#nodeMonitorGracePeriod: 40s
#podEvictionTimeout: 5m


CLUSTER_NAME: 'kubernetes'
KUBE_VERSION: 'v1.13.4'
ETCD_version: 'v3.3.12'
# 是否使用二进制
kube_proxy_bin: true 
flanneld_bin: true

Net_Choose: flannel  # 暂时只有flannel,后续增加其他的

flannel_img: v0.11.0-amd64
# or set the value to 'host-gw'
flannel_type: vxlan
flanneld_healthz_port: 8471


infra_image: 'registry.cn-hangzhou.aliyuncs.com/google_containers/pause-amd64:3.1'
KUBE_APISERVER: https://{% if groups['master'] | length !=1 %}{{ VIP }}:8443{% else %}{{ hostvars[groups['master'][0]].inventory_hostname }}:6443{% endif %}
